### ISSUE TITLE
Is this cookbook compatible with Amazon Linux? -  Platform not supported

### ISSUE THREAD

**Issue by sbhakta99** [kgrubb/verdaccio-cookbook#11]
Is this cookbook compatible with Amazon Linux? -  Platform not supported

Getting following error with Amazon Linux and Amazon Linux 2
   ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/usf_verdaccio/recipes/default.rb
       ================================================================================

       RuntimeError
       ------------
       Platform not supported

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/verdaccio/recipes/verdaccio.rb:84:in `from_file'
         /tmp/kitchen/cache/cookbooks/verdaccio/recipes/default.rb:8:in `from_file'
         /tmp/kitchen/cache/cookbooks/usf_verdaccio/recipes/default.rb:11:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/verdaccio/recipes/verdaccio.rb:

        77:    else
        78:      template '/etc/init/verdaccio.conf' do
        79:        source 'verdaccio.conf.erb'
        80:        notifies :restart, 'service[verdaccio]', :delayed
        81:      end
        82:    end
        83:  else
        84>>   raise 'Platform not supported'
        85:  end
        86:
        87:  service 'verdaccio' do
        88:    supports status: true, restart: true, reload: false
        89:    action [:enable, :start]
        90:  end
        91:

       System Info:
       ------------
       chef_version=13.6.4
       platform=amazon
       platform_version=2
       ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
       program_name=chef-solo worker: ppid=5051;start=22:35:14;
       executable=/opt/chef/bin/chef-solo

**Comment by kgrubb** [comment]
I haven't worked on this cookbook in quite a while, so it is likely outdated and possibly broken. I'm currently working on updating it, progress can be viewed here: https://github.com/verdaccio/verdaccio-cookbook/pull/12

**Comment by kgrubb** [comment]
hey @sbhakta99, I just released 3.0.0 on the [chef supermarket](https://supermarket.chef.io/cookbooks/verdaccio). It should have all of the updated requirements for verdaccio, and should be compatible with amazon linux 2!

**Comment by juanpicado** [comment]
Thanks @kgrubb you are the best !!
