### ISSUE TITLE
Lib and Var folders are not being created

### ISSUE THREAD

**Issue by lazygabe** [kgrubb/verdaccio-cookbook#2]
[Code](https://github.com/kgrubb/verdaccio-cookbook/blob/ec0c5a592afea7be0bab58312c5e3d645eec0b0d/recipes/verdaccio.rb#L16-L19) here should be:
`[
  node['verdaccio']['logdir'],
  node['verdaccio']['datadir']
].each do |create_dir|`
Otherwise, it will be treated as words instead of variables

**Comment by kgrubb** [comment]
Fixed in pr #3. Thanks for the catch & fix!
