### ISSUE TITLE
htpasswd file join incorrect

### ISSUE THREAD

**Issue by pmacdougall** [kgrubb/verdaccio-cookbook#8]
This line should use double quotes `content htpasswdEntries.join("\n")`
https://github.com/verdaccio/verdaccio-cookbook/blob/dae2cd6fd04e95804867edebf50747e04c685d72/recipes/verdaccio.rb#L37

As it is now, the htpasswd file contains one line with literal "\n" characters instead of actual newlines.

**Comment by juanpicado** [comment]
hi @pmacdougall does this deserves a PR?

**Comment by DanielRuf** [comment]
Already fixed in https://github.com/verdaccio/verdaccio-cookbook/pull/9 so I'm closing this issue.
